### ISSUE TITLE
Selected and Unselected Item Padding Differs

### ISSUE THREAD

**Issue by ghost** [elkrien/catppuccin-grub#1]
As the title says. I don't know if it's a normal behavior, but just a little bit annoying *personally*.

**Comment by elkrien** [comment]
> As the title says. I don't know if it's a normal behavior, but just a little bit annoying _personally_.

I think i fixed it. Please test.

**Comment by ghost** [comment]
> > As the title says. I don't know if it's a normal behavior, but just a little bit annoying _personally_.
> 
> I think i fixed it. Please test.

Yes it's fixed, thanks. But lastly, as a background you use flat colored image. Instead of image, can't you just replace it with one color?

**Comment by elkrien** [comment]
> > > As the title says. I don't know if it's a normal behavior, but just a little bit annoying _personally_.
> > 
> > 
> > I think i fixed it. Please test.
> 
> Yes it's fixed, thanks. But lastly, as a background you use flat colored image. Instead of image, can't you just replace it with one color?

Thx - I did like You suggested. I updated theme and also added You to Thanks To section in README.md. Let me know if You are ok with this.

**Comment by ghost** [comment]
Looks perfect, thank you!

**Comment by ghost** [comment]
I found a problem after your changes. In the menu, if you select another menu (advanced options, for example) and go back and start the operating system, GRUB will throw an error. Unfortunately I can't send screenshots right now.

**Comment by elkrien** [comment]
> I found a problem after your changes. In the menu, if you select another menu (advanced options, for example) and go back and start the operating system, GRUB will throw an error. Unfortunately I can't send screenshots right now.

I was able to reproduce this error - it happens when desktop-color is used. When background.png is used everything works ok on my machine. I have returned to previous version with image as background.

**Comment by ghost** [comment]
Okay then. Shall I close the issue?
