### ISSUE TITLE
Windows 11 icon request

### ISSUE THREAD

**Issue by dicktivity** [elkrien/catppuccin-grub#11]
Hello, i have Ubuntu and Windows 11 dual boot.
Unfortunately there is no windows 11 icon, only the old windows icon in icons folder.
So i attempt to create windows 11 icon and manually add it to icons folder.
But the grub theme doesn't pick it up, there is no icon beside my Windows 11 entry menu.
I already matched the icon name and entry menu class "windows11"

My /etc/grub.d/40_custom file:

```
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Windows 11" --class windows11 {
   search --no-floppy --set=root --fs-uuid AA9F-2C38
   chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "Reboot" --class restart {
        reboot
}

menuentry "Shut Down" --class shutdown {
        halt
}
```
windows11.png
![windows11](https://user-images.githubusercontent.com/30734552/209909912-d70cd310-b6e9-4737-8048-11ba0f37bfec.png)

My Grub:
![Screenshot from 2022-12-29 13-46-13](https://user-images.githubusercontent.com/30734552/209914750-c0e5c57a-5027-4346-943c-4282729bf2f2.png)

**Comment by elkrien** [comment]
What is the name of the class for windows in /boot/grub/grub.cfg? 
I don't have windows on any of my computers but as I know it looks for the png with the name as it is in /boot/grub/grub.cfg.

**Comment by dicktivity** [comment]
Thanks for the reply elkrien.
The class in grub.cfg is the same as in /etc/grub.d/40_custom

```
-
-
-
### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Windows 11" --class windows11 {
   search --no-floppy --set=root --fs-uuid AA9F-2C38
   chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}

menuentry "Reboot" --class restart {
	reboot
}

menuentry "Shut Down" --class shutdown {
	halt
}
### END /etc/grub.d/40_custom ###
-
-
-
```

I should add that i don't have this issue with [distro-grub-theme](https://k1ng.dev/distro-grub-themes/preview).
Screenshot:
![Screenshot from 2022-12-29 15-55-24](https://user-images.githubusercontent.com/30734552/209927687-53e4382f-35b0-499f-be78-99a810ad5e4b.png)

Do you think it's because the image (png) format? I create the windows 11 icon using [Photopea](https://www.photopea.com/) .

**Comment by dicktivity** [comment]
Okay so i went back and just straight up copy the windows 11 icon from other theme and paste it to catppuccin theme and it worked.
I guess the issue is indeed the image format.
Will try another image editor later.

![Screenshot from 2022-12-29 16-27-30](https://user-images.githubusercontent.com/30734552/209932067-990feb7a-c883-4c95-8642-87967c123207.png)

**Comment by elkrien** [comment]
Great. How about a PR with new icon? If not could You attach icon file that works and I will upload it to this repo?

**Comment by dicktivity** [comment]
Alright just created a new PR.
I make the icon using corel draw this time and it worked.

![Screenshot from 2022-12-29 20-43-35](https://user-images.githubusercontent.com/30734552/209962267-144248fe-cdb0-488e-8fcc-e07fe764a853.png)

Thank you for the response elkrien.
Closing this issue.
