### ISSUE TITLE
Doesn't work on Fedora, readme needs updated instructions

### ISSUE THREAD

**Issue by 42willow** [elkrien/catppuccin-grub#14]
I know this is the same with the other themes too, but Fedora's GRUB is weird...

I'll try and get it to work and then send my answer here, unless someone helps me before then.

**Comment by justTOBBI** [comment]
So the instructions in the README arent working anymore?

**Comment by 42willow** [comment]
I think they are still relevant, but setting up any grub theme with a fresh Fedora install isn't working for me...


The themes folder didn't even exist in the directory.


I'm trying this -> https://www.reddit.com/r/Fedora/comments/102h2bl/guide_setting_a_custom_efi_grub_theme/ now and I'll let you know if it works.

**Comment by 42willow** [comment]
I couldn't get it to work :/

**Comment by 42willow** [comment]
https://www.youtube.com/watch?v=vC5YyTQXKI0

At the end of this video, this command works to update the grub config and set the theme!!!
`sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg`

as opposed to the recommended 
`sudo grub2-mkconfig -o /boot/grub2/grub.cfg`

Why there are two grub configs, with one working and one not I have no clue :thinking:

**Comment by 42willow** [comment]
hmm never mind
```
sudo grub2-mkconfig -o /etc/grub2.cfg

sudo grub2-mkconfig -o /etc/grub2-efi.cfg 
```
also works and is recommended.. weird

can't really reproduce anymore
