### ISSUE TITLE
Default grub menu appears momentarily

### ISSUE THREAD

**Issue by meminens** [elkrien/catppuccin-grub#15]
At boot, I am presented with the catpuccin theme for 1 second (no issues with at all) but the Debian's default grub menu with cyan background appears maybe for half a second after the 1 second timeout. And then system resumes normal boot. Any thoughts why this might be happening?

Grub config is copied below:

```
GRUB_DEFAULT=0
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT='quiet'
GRUB_CMDLINE_LINUX=''
GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha-grub-theme/theme.txt"
GRUB_GFXMODE=2560x1440
```

**Comment by isabelincorp** [comment]
I can't replicate this on my own hardware, but I'm figuring this could be happening because you have Debian branding embedded within your grub installation, but with a quick search you should be able to remove it to a clean/fresh grub install.
