### ISSUE TITLE
ventoy中镜像名字比较长的时候不能显示完全，该调整哪个选项呢

### ISSUE THREAD

**Issue by runishiwo** [elkrien/catppuccin-grub#19]
![111111111111111111](https://github.com/catppuccin/grub/assets/66987131/516e9fa5-4857-4a1d-a297-565ea20e6350)

**Comment by runishiwo** [comment]
调整哪个选项可以显示全部名字

**Comment by rubyowo** [comment]
we speak english here

**Comment by justTOBBI** [comment]
Title: When the image name in ventoy is relatively long and cannot be displayed completely, which option should be adjusted?

**Comment by runishiwo** [comment]
solved
