### ISSUE TITLE
Grub's boot-menu cuts off NixOS generation text

### ISSUE THREAD

**Issue by egirlcatnip** [elkrien/catppuccin-grub#21]
Catppuccin grub's boot-menu box width is 480 pixels - 25% of 1920px screen.
This is too narrow to show the full NixOS boot generation text

Currently looks like this:
![image](https://github.com/catppuccin/grub/assets/26607304/1193fe2f-497b-4422-bee1-83f035aebb0e)

I propose an increase to 35% or 40%, which should be enough, either as a percentage or a value of 672 or 768 pixels

Link to the corresponding catppuccin/nix repo's issue:
[Grub's boot-menu cuts off NixOS generation text #223](https://github.com/catppuccin/nix/issues/223#issue-2345040628)

**Comment by Jojobinx17** [comment]
You can change the width property of the boot menu.

In your theme file (`/usr/share/grub/themes/catppuccin-<flavor>-grub-theme/theme.txt`), and inside the `boot_menu` section, modify these two lines:

`left = 50%-240` --> `left = 50%-480`
`width = 480` --> `width = 960`

This will double the width of the boot options. Modify them as you see fit.

Finally, update grub with the new config: `sudo grub-mkconfig -o /boot/grub/grub.cfg`, then use `sudo reboot` to view your changes.

**Comment by DoriKyll** [comment]
I just made a pull reauest for a similar issue I was having.
I widened the menus to 780px.

If you have time to check and see if this PR fixes your issue.
here's the link to the PR I made:
[#24]

**Comment by isabelincorp** [comment]
Issue fixed with #24.
Also resolves https://github.com/catppuccin/nix/issues/223 as completed.
