### ISSUE TITLE
Mixed/Preview background as an option

### ISSUE THREAD

**Issue by Jacksaur** [elkrien/catppuccin-grub#22]
I really like the [Combined preview image](https://github.com/catppuccin/grub/blob/main/assets/grub.png?raw=true) you made to illustrate all the background colours together. It'd be really nice if it was available as its own background choice.

**Comment by isabelincorp** [comment]
Hi @Jacksaur,
Thanks for opening this issue. You can replicate the look by using our very own [catwalk](https://github.com/catppuccin/catwalk), which has a composite feature. With it, you can merge the multiple flavours into one image file, then throw it into the config. Additional background images aren't planned, however, as explained in https://github.com/catppuccin/rofi/issues/29#issue-2699686395.
