### ISSUE TITLE
NIXOS CONFIG

### ISSUE THREAD

**Issue by salko-ua** [elkrien/catppuccin-grub#23]
is it possible to write this topic declaratively on nixos

**Comment by aquifolly** [comment]
https://github.com/catppuccin/nix

https://nix.catppuccin.com/options/nixos-options.html#bootloadergrubcatppuccinenable

**Comment by salko-ua** [comment]
these links are useless here. the first sets the theme to system, and the second to grub, but not to the grub theme itself

**Comment by Ex-32** [comment]
If you want more customization, you can just write your own derivation for `boot.loader.grub.theme`. It's not very difficult, here's the one I wrote to adjust the size and font: https://github.com/Ex-32/nixos-config/blob/154080f376b045fb08cf04f4b1f69777488c80bb/lib/grub.nix#L29-L60

**Comment by salko-ua** [comment]
thank you very much for your time. I will try to write something

> If you want more customization, you can just write your own derivation for `boot.loader.grub.theme`. It's not very difficult, here's the one I wrote to adjust the size and font: https://github.com/Ex-32/nixos-config/blob/154080f376b045fb08cf04f4b1f69777488c80bb/lib/grub.nix#L29-L60
