### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by Shagon94** [elkrien/catppuccin-grub#25]
This doesn't seem to work on debian 12.

I've added:

```
GRUB_GFXMODE=3440x1440
GRUB_DISABLE_OS_PROBER=false
GRUB_TERMINAL_OUTPUT="console"
```

and tried both the /usr/share method and the /boot method following https://github.com/catppuccin/grub?tab=readme-ov-file#usage. In both cases the theme is not applied. The screen does change to the desired size though.

Can you please clarify if there's anything else required to make this work? How would I go about troubleshooting why the theme isn't applied?

**Comment by Shagon94** [comment]
Not sure if it's because of the configuration:

```env
/dev/nvme0n1p3  196G   65G  121G  35% /
/dev/sda2        96M   33M   64M  35% /boot/efi

❯ ll /boot/grub/themes/
drwxr-xr-x - root 12 Sep 22:48 catppuccin-frappe-grub-theme

```

`/etc/default/grub` looks fine:

```env
GRUB_DEFAULT="Windows Boot Manager (on /dev/sda2)"
GRUB_TIMEOUT="5"
GRUB_DISTRIBUTOR="`lsb_release -i -s 2> /dev/null || echo Debian`"
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
GRUB_DISABLE_OS_PROBER="false"
GRUB_GFXMODE="3440x1440"
GRUB_SAVEDEFAULT="false"
GRUB_THEME="/boot/grub/themes/catppuccin-frappe-grub-theme/theme.txt"
GRUB_GFXMODE="3440x1440"
GRUB_TERMINAL_OUTPUT="console"
export GRUB_COLOR_NORMAL="light-gray/black"
export GRUB_COLOR_HIGHLIGHT="magenta/black"
```

grub is up-to-date:

```shell
❯ grub-mkconfig --version
grub-mkconfig (GRUB) 2.06-13+deb12u1
```

**Comment by Shagon94** [comment]
In the docs it states:

> Q: "How can I make Grub detect my theme?"
> A: Make sure to comment the following line in /etc/default/grub:
> GRUB_TERMINAL_OUTPUT="console"

To clarify, should `GRUB_TERMINAL_OUTPUT="console"` be commented or not? the wording is somewhat confusing considering the example 😅

**Comment by sgoudham** [comment]
@isabelincorp do you have any further insights into why it might not be working anymore? 

I believe the `GRUB_TERMINAL_OUTPUT="console"` should be commented @Shagon94

**Comment by Shagon94** [comment]
Works as expected when commenting out `GRUB_TERMINAL_OUTPUT="console"`. Created https://github.com/catppuccin/grub/pull/26 to make it a bit clearer

**Comment by isabelincorp** [comment]
> @isabelincorp do you have any further insights into why it might not be working anymore?
> 
> I believe the `GRUB_TERMINAL_OUTPUT="console"` should be commented @Shagon94

@sgoudham Grub sometimes has really specific settings you have to change if this is your first time in the ballpark. Which sometimes requires the config files to be changed after an update, so I see this issue as completely normal. 

Thanks for raising and solving the issue @Shagon94 !
