### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by sophiiss** [elkrien/catppuccin-grub#4]
`GRUB_THEME="/usr/share/grub/themes/catppuccin-grub-theme/theme.txt"`
`#GRUB_TERMINAL_OUTPUT="console"`

It still shows the default grub view.

**Comment by elkrien** [comment]
> `GRUB_THEME="/usr/share/grub/themes/catppuccin-grub-theme/theme.txt"`
> 
> `#GRUB_TERMINAL_OUTPUT="console"`
> 
> 
> 
> It still shows the default grub view.

Can You paste here what is an output of updating guru config command: `sudo grub-mkconfig -o /boot/grub/grub.cfg`?

**Comment by ghost** [comment]
Had a similar issue where putting the theme folder into /usr didn't work on my encrypted Gentoo install (grub-mkconfig wouldn't detect the theme at all).
Replacing /usr/share/ with /boot/ ended up working fine on my end.

**Comment by PoorPocketsMcNewHold** [comment]
Can confirm on Fedora as well, as it just copy the configuration in its own /boot directory, surely because it allows to access the grub configuration, before decrypting the actual hard-drive.

Might need a README.md change if some could confirm such a theory, if they have an encrypted drive.

```
root@VIX:/boot/grub2# ls
fonts  grub.cfg  grubenv  theme
root@VIX:/boot/grub2# cd theme/
root@VIX:/boot/grub2/theme# ls
background.png  font.pf2  icons  logo.png  select_c.png  select_e.png  select_w.png  theme.txt
```
