### ISSUE TITLE
Grub theme acting weird

### ISSUE THREAD

**Issue by ghost** [elkrien/catppuccin-grub#5]
Followed the install instructions (I'm using EFI and dual booting windows so i executed the following command)
`sudo grub-mkconfig -o /boot/efi/EFI/ubuntu/grub.cfg`
The boot menu is looking pretty weird but still functional (see attached), any way to fix this?

![1651209991516](https://user-images.githubusercontent.com/70006643/165889456-9eebbeb8-6801-4672-ba53-cfcde46b64b2.JPEG)

![1651209991566](https://user-images.githubusercontent.com/70006643/165889450-d89f94bc-97fc-4fd1-868c-b41fa8f52f4a.JPEG)

**Comment by elkrien** [comment]
It looks that theme was not loaded and grub is using default theme. You need to copy catppuccin theme to a proper folder. Can You please run ```sudo grub-mkconfig -o /boot/efi/EFI/ubuntu/grub.cfg``` again and paste here output?
You can also try to copy theme to:
```sudo cp -r catppuccin-grub-theme /boot/grub/themes/``` and then run above command again and check if it works.
