### ISSUE TITLE
Alternative ascii cat logo

### ISSUE THREAD

**Issue by Kettukaa** [elkrien/catppuccin-grub#7]
It would be cool if we can get the [ascii cat](https://github.com/catppuccin/alacritty/raw/main/assets/screenshot.webp) that are in several screenshots and [wallpapers](https://github.com/catppuccin/wallpapers/tree/main/minimalistic) as an alternative logo

```
  ／l、
（ﾟ､ ｡７
   l、ﾞ~ヽ
  じしf_,)ノ
```

**Comment by isabelincorp** [comment]
Not planned, we don't own ascii art but we do own the logo already. In order to integrate this it would most likely require converting the cat into a questionalbly scaled png that might not look great depending on the display.
